version: 0.2

phases:
  install:
    commands:
      - echo Installing dependencies...
      - yum update -y || true
  pre_build:
    commands:
      - echo Pre-build phase...
  build:
    commands:
      - echo Build phase...
      - echo "Hello from CodeBuild" > output.txt
  post_build:
    commands:
      - echo Post-build phase complete.
artifacts:
  files:
    - '**/*'
  discard-paths: yes
