version:0.2

phases:
  install:
    commands:
      - echo installing dependencies...
      - npm install
  
  build:
    commands:
      - echo Running tests
      - npm test
      - scho Build complete!

  artifacts:
    files:
      - '**/*'
