version: 0.2

phases:
  install:
    commands:
      - echo Installing dependencies...
      - echo Skipping apt-get since it is not supported in this environment.
      - yum update -y || true
  pre_build:
    commands:
      - echo Pre-build phase...
  build:
    commands:
      - echo Build phase...
      - echo "Build in progress"
  post_build:
    commands:
      - echo Post-build phase complete.
artifacts:
  files:
    - '**/*'
