version: 0.2

phases:
  install:
    commands:
      - echo Installing dependencies...
      - yum update -y || true
  pre_build:
    commands:
      - echo Pre-build phase...
  build:
    commands:
      - echo This build will fail intentionally...
      - fakecommand
      - echo "This is a change to test automatic trigger in codepipeline" > output.txt
  post_build:
    commands:
      - echo Post-build phase complete.
artifacts:
  files:
    - output.txt
  discard-paths: yes
